#!C:\Users\sverremh\source\repos\MatchingWrapper\MatchingWrapper\PythonFiles\matching_env\Scripts\python.exe
"""Small script to execute the igraph command line interface"""
from igraph.app.shell import main
main()
